import mockAbi from "./mockAbi.json";

// ---------------------------------------------------------------------------
// CONTRACT ADDRESS
// Replace this with the real deployed address once the Protocol Architect
// runs their Hardhat deployment script and shares the output address.
//
// How to get it: After `npx hardhat run scripts/deploy.js --network sepolia`,
// the terminal will print: "Contract deployed to: 0x..."
// Paste that address here and set IS_MOCK_ABI to false.
// ---------------------------------------------------------------------------
export const CONTRACT_ADDRESS = "0x0000000000000000000000000000000000000000";

// ---------------------------------------------------------------------------
// ABI SOURCE FLAG
// Flip this to false once the real ABI arrives from the Protocol Architect.
// The real ABI will be the artifact file generated by Hardhat after compilation,
// found at: /artifacts/contracts/YourContract.sol/YourContract.json
// Import the "abi" field from that file and replace mockAbi below.
// ---------------------------------------------------------------------------
export const IS_MOCK_ABI = true;

// ---------------------------------------------------------------------------
// CONTRACT_ABI
// This is the single export all hooks import. When the real ABI is ready,
// you only need to update this one file — every hook stays the same.
// ---------------------------------------------------------------------------
export const CONTRACT_ABI = mockAbi;
